Migrate tests.sh to run_tests.py
TheVaultdweller13/imperivm pull request #3
Opened 2024-12-28 20:37 UTC by TheVaultdweller13

2025-01-01 17:56 UTC, Nirei commented on Pipfile
> -test = "./test.sh"
Why remove this?

2025-01-01 17:57 UTC, Nirei commented on .gitignore
> +# Unit test / coverage reports
This change looks accidental.

2025-01-01 17:58 UTC, Nirei requested changes
Could we we keep the pipenv `test` script and make it call the python script instead?

It makes the DX a bit better to be able to invoke tests through `pipenv run tests`.

2025-01-01 18:09 UTC, TheVaultdweller13 commented on .gitignore
> +# Unit test / coverage reports
Yep

2025-01-01 18:13 UTC, TheVaultdweller13 commented on Pipfile
> -test = "./test.sh"
This is how it ended up after trying. It's now fixed.

2025-01-02 01:04 UTC, Nirei approved these changes
A++

2025-01-02 01:06 UTC, merged