Add comments support
TheVaultdweller13/imperivm pull request #4
Opened 2024-12-31 18:29 UTC by TheVaultdweller13

2025-01-01 17:35 UTC, Nirei commented on parser.py
> +    def remove_comments(program: str):
Let's use object oriented design here. In the future we may want to support a variety of preprocessors and having a static method in a class makes this rigid and difficult to change.

Furthermore I'd argue that exposing a method called `remove_comments` kind of defeats the purpose of having a class at all. The preprocessor class should `preprocess` and that's it. The actual operations that happen inside it should not leak outside.

2025-01-01 17:37 UTC, Nirei commented on parser.py
> +            cleaned_line = re.sub(r'#.*$', '', line).strip()
Don't strip lines. This will make the parser error reporting useless: you no longer know which column a problem happens at because whitespaces are removed from the original line.

2025-01-01 17:40 UTC, Nirei commented on parser.py
> +            if cleaned_line:
In what cases can cleaned line be false? This doesn't look good either. If I understand correctly you are removing empty lines. The same way as with `strip` you lose important information and make the parser unable to correctly report errors because line numbers will no longer match. Every line in the original should be there in the preprocessed text.

2025-01-01 17:42 UTC, Nirei commented on parser.py
> +        cleaned_lines = []
Why not edit the original lines array? It'd save memory.

2025-01-01 17:44 UTC, Nirei requested changes
I propose we use a more object-oriented design for the preprocessor.
I also found a couple issues in the preprocessing related to original code location information being lost.

2025-01-01 17:47 UTC, Nirei commented on parser.py
> +    def remove_comments(program: str):
In my head this would look something like this:

```suggestion
    def preprocess(self, program: str):
```

2025-01-01 17:49 UTC, Nirei commented on parser.py
> +        program = PreProcessor.remove_comments(program)
For better OO, we could inject the preprocessor dependency in the constructor to this class. This allows us to have different preprocessors if necessary, for instance. It also allows for easier unit testing because you can inject a testing double.

2025-01-01 17:50 UTC, Nirei commented on parser.py
>      def __init__(self, grammar=grammar.imperivm, visitor=visitor.ImperivmVisitor()):
Example with dep. injection.

```suggestion
    def __init__(self, grammar=grammar.imperivm, visitor=visitor.ImperivmVisitor(), preprocessor=PreProcessor()):
```

2025-01-01 17:50 UTC, Nirei commented on tests/comments.imp
> +        # PRINT A HELLO WORLD... IN LATIN
Why are the comments yelling? :cry:

2025-01-01 17:52 UTC, Nirei commented on parser.py
> +class PreProcessor:
Absolute nitpick but `Preprocessor` is a single word. This camel-casing makes me a bit itchy. :confused:

2025-01-01 17:53 UTC, Nirei commented
Excellent work. This is a fundamental feature of the language so it's very important to get it right. Let's refine a bit before merging if you don't mind.

2025-01-01 19:17 UTC, TheVaultdweller13 commented on parser.py
> +        program = PreProcessor.remove_comments(program)
How about something like this?
![imagen](https://github.com/user-attachments/assets/162f2d42-dc3f-4633-9bc4-423663f79862)

This way, we could have a `Preprocessor` interface with multiple implementations, depending on what we want to process, each with its own process(program) method.

P.S.: For now, I’d put it in the same file since we don’t have a folder structure, but we should start thinking about refactoring and creating one

2025-01-01 19:21 UTC, TheVaultdweller13 commented on tests/comments.imp
> +        # PRINT A HELLO WORLD... IN LATIN
They try to be part of the code, but fail miserably.

2025-01-02 00:53 UTC, TheVaultdweller13 commented on parser.py
> +            if cleaned_line:
Added this due to issues with some comments (e.g., comments before the subroutine or at the end of the text) that were causing problems with the grammar, presumably because they leave line breaks that we don't allow.

2025-01-02 01:33 UTC, Nirei commented on parser.py
> +        self.preprocessor = PreprocessorPipeline([CommentsPreprocessor()])
To allow dependency injection this should be received in a parameter, same as visitor and grammar. You can provide a default value for ease of use.

2025-01-02 01:35 UTC, Nirei commented on parser.py
> +class PreprocessorPipeline:
This is a nice idea. I would go even further and make it implement the `Preprocessor` interface as well. Also these three classes could probably live in a `preprocessor.py` file.

2025-01-02 01:37 UTC, Nirei approved these changes
Nitpicks but you can go to sleep and catch them in a separate PR tomorrow.

2025-01-02 01:43 UTC, TheVaultdweller13 commented on parser.py
> +class PreprocessorPipeline:
I thought about the interface, but I didn't really like the fact that the pipeline is not, as such, an implementation of the preprocessor. I don't know, I don't really have a final preference on this subject.

2025-01-02 01:46 UTC, Nirei commented on parser.py
> +            lambda cleaned_line: cleaned_line,
What's this lambda doing...?

2025-01-02 01:48 UTC, Nirei commented on parser.py
> +class PreprocessorPipeline:
It is indeed an implementation of the preprocessor as the preprocessor is an interface that gets some text an proprocesses it and that's exactly what the pipeline does. It simply uses a special strategy to accomplish it based on calling other Preprocessor implementors. :vulcan_salute:

2025-01-02 02:20 UTC, TheVaultdweller13 commented on parser.py
> +            lambda cleaned_line: cleaned_line,
To remove the empty lines that were giving me problems (an empty string gives false). It is now solved with the change of the program grammar

2025-01-02 02:20 UTC, merged